version: '3'
services:
  db:
    image: postgres
    container_name: go-tasks-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - go_postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network
  app:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile.dev
    container_name: go-tasks-app
    depends_on:
      - db
    env_file:
      - .env  
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8000:8000"
    networks:
      - todo-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - ${VITE_API_URL}
    depends_on:
      - app
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  go_postgres_data:
  